### ISSUE TITLE
Add Sentry Monitoring

### ISSUE THREAD

**Issue by devinmatte** [Dr-N0/Jumpstart#2]
Send critical/important errors to sentry via new sdk. There are plugins for [flask](https://docs.sentry.io/platforms/python/flask/) and [sqlalchemy](https://docs.sentry.io/platforms/python/sqlalchemy/)

https://docs.sentry.io/error-reporting/quickstart/?platform=python

By adding this, every new or frequent stack trace will be sent to slack so we can more quickly tackle bugs and overall improve the application

**Comment by Dr-N0** [comment]
Finished
