### ISSUE TITLE
Add Pylinting

### ISSUE THREAD

**Issue by devinmatte** [Dr-N0/Jumpstart#3]
We use pylint in a few of our applications to enforce code style and force our applications to have good code practices.

If anything it will teach you good python practices as you write the application and will make reading the code easier to anyone who takes a look in the future because it'll all uniform.

https://www.pylint.org/

Packet Example:
https://github.com/ComputerScienceHouse/packet/blob/develop/.pylintrc
https://github.com/ComputerScienceHouse/packet/blob/develop/.travis.yml

**Comment by Dr-N0** [comment]
Finished
